### ISSUE TITLE
CUDA not support on Mac

### ISSUE THREAD

**Issue by ab-ram-01** [CAMMA-public/rendezvous#12]
When I try to run the code using the CholecT45 dataset, I receive the error:

raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

It looks like "
NVIDIA® CUDA Toolkit 11.6 no longer supports development or running applications on macOS."

Has anyone been able to find a work around to this issue?

**Comment by nwoyecid** [comment]
Closed for lack of activities
