### ISSUE TITLE
download pretrain weight

### ISSUE THREAD

**Issue by BigBuffa1o** [CAMMA-public/rendezvous#14]
Hi.i try to download the pretrain weight to reproduce the result but i failed at every file,here is the problem how can i solve it?Thanks in advance.

![01e8a8ff-2d55-4d7a-b824-74a9e7bcee1c](https://user-images.githubusercontent.com/118952497/228192704-08e1e3f4-f5b6-43ea-9bae-32396b6ad5b3.jpeg)

**Comment by csEylLee** [comment]
> Hi.i try to download the pretrain weight to reproduce the result but i failed at every file,here is the problem how can i solve it?Thanks in advance.
> 
> ![01e8a8ff-2d55-4d7a-b824-74a9e7bcee1c](https://user-images.githubusercontent.com/118952497/228192704-08e1e3f4-f5b6-43ea-9bae-32396b6ad5b3.jpeg)

I also meet this problem. Have you solved it?

**Comment by nwoyecid** [comment]
The download URL for a particular weight looks incorrect, others are fine. Please use correct and working ones. I will check the correct URL for the wrong one and update it later.

**Comment by nwoyecid** [comment]
Correct links updated.
