### ISSUE TITLE
Implementation of random scaling

### ISSUE THREAD

**Issue by csEylLee** [CAMMA-public/rendezvous#15]
In your paper you writed:"We employed random scaling [0.5, 1.5]", but there is no such method in the released code. Can you provide the implementation of random scaling? 
I tried to code a random scale function and followed all the hyperparameter settings in the paper, but I still could not get the results in the paper.

**Comment by csEylLee** [comment]
--------------------------------------------------
Mean AP:  I  |  V  |  T  |  IV  |  IT  |  IVT 
:::::: : 0.8274 | 0.5316 | 0.3626 | 0.3070 | 0.2689 | 0.2105 
==================================================

**Comment by nwoyecid** [comment]
This repo is a re-implementation of the original RDV. It does not exactly use everything as in the RDV paper, e.g. random scaling. If you implement it, you can make a pull request to contribute your implementation to this repo.
