### ISSUE TITLE
Reproduce problem

### ISSUE THREAD

**Issue by NGC2237-cn** [CAMMA-public/rendezvous#22]
When I reproduced the code for the RDV article(RDV split), my result remains about 0.6784 | 0.4404 | 0.2609 | 0.1923 | 0.1316 | 0.0994 ,which are largely different from the official result 92.0 60.7 38.3 39.4 36.9 29.9, I want to know did you make any changes to the released code, or is there any difference between the actual Settings and the default ones?

**Comment by nwoyecid** [comment]
Dear user,

Visit the published paper for the details on the hyperparameters used for each type of results.

Thanks

**Comment by ntlm1686** [comment]
@Aawaqqqqq 
I got quite similar results as yours.

I: 0.6692356875905586
V: 0.4106192227280994
T: 0.20920773377057966

Have you been able to figure this out?

**Comment by labdeeman7** [comment]
I gave what worked for me here. https://github.com/CAMMA-public/rendezvous/issues/26#issuecomment-2796104646
