### ISSUE TITLE
reproduced result

### ISSUE THREAD

**Issue by gshuangchun** [CAMMA-public/rendezvous#3]
When I used the default hyperparameters, I got a bad result by using pytorch. Could you please release the hyperparameters used by the best results?

My results are as follows:
python run.py --train --kfold 1 --gpu 0
--------------------------------------------------
Mean AP:  I  |  V  |  T  |  IV  |  IT  |  IVT 
:::::: : 0.8028 | 0.5914 | 0.3454 | 0.3218 | 0.2888 | 0.2299 

python run.py --train --kfold 2 --gpu 0
--------------------------------------------------
Mean AP:  I  |  V  |  T  |  IV  |  IT  |  IVT 
:::::: : 0.8129 | 0.5572 | 0.3334 | 0.2865 | 0.2568 | 0.2033 

python run.py --train --kfold 3 --gpu 0
--------------------------------------------------
Mean AP:  I  |  V  |  T  |  IV  |  IT  |  IVT 
:::::: : 0.8561 | 0.5684 | 0.3352 | 0.3892 | 0.2961 | 0.2475 

python run.py --train --kfold 4 --gpu 0
--------------------------------------------------
Mean AP:  I  |  V  |  T  |  IV  |  IT  |  IVT 
:::::: : 0.8188 | 0.5247 | 0.3109 | 0.2975 | 0.2667 | 0.2086

**Comment by nwoyecid** [comment]
Please, check the published papers for their used hyper-parameters.
Also, note, the original papers use different augmentation style per epoch, which is different from the simplified dataloader in the git repo.

**Comment by csEylLee** [comment]
> When I used the default hyperparameters, I got a bad result by using pytorch. Could you please release the hyperparameters used by the best results?
> 
> ## My results are as follows:
> python run.py --train --kfold 1 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8028 | 0.5914 | 0.3454 | 0.3218 | 0.2888 | 0.2299
> 
> ## python run.py --train --kfold 2 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8129 | 0.5572 | 0.3334 | 0.2865 | 0.2568 | 0.2033
> 
> ## python run.py --train --kfold 3 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8561 | 0.5684 | 0.3352 | 0.3892 | 0.2961 | 0.2475
> 
> ## python run.py --train --kfold 4 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8188 | 0.5247 | 0.3109 | 0.2975 | 0.2667 | 0.2086

Have you solved it? I meet the same problem. 
前辈，请问您这个问题解决了吗？我遇到了相同的问题。

**Comment by DoctorMango** [comment]
The same question, have you solved it, I tried some parameters but I don't get the same results. Could you please share your hyperparameters? Especially the `pretrain_dir`,`initial_learning_rates`, I can't make sure my parameters.

**Comment by DoctorMango** [comment]
> When I used the default hyperparameters, I got a bad result by using pytorch. Could you please release the hyperparameters used by the best results?
> 
> ## My results are as follows:
> python run.py --train --kfold 1 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8028 | 0.5914 | 0.3454 | 0.3218 | 0.2888 | 0.2299
> 
> ## python run.py --train --kfold 2 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8129 | 0.5572 | 0.3334 | 0.2865 | 0.2568 | 0.2033
> 
> ## python run.py --train --kfold 3 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8561 | 0.5684 | 0.3352 | 0.3892 | 0.2961 | 0.2475
> 
> ## python run.py --train --kfold 4 --gpu 0
> Mean AP: I | V | T | IV | IT | IVT :::::: : 0.8188 | 0.5247 | 0.3109 | 0.2975 | 0.2667 | 0.2086

hello, can i get your hyperparameters, I can't reproduce the paper result, so I want to reproduce your result first.
