### ISSUE TITLE
sklearn version

### ISSUE THREAD

**Issue by gshuangchun** [CAMMA-public/rendezvous#4]
Hi, 
what is the sklearn version?
when I test the same trained model, the scikit-learn==1.0.2 is
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

mAPI | mAPV | mAPT | mAPIV | mAPIT | mAPIVT
-- | -- | -- | -- | -- | --
84.04 | 52.18 | 32.49 | 33.83 | 26.36 | 21.9

</body>
</html>

while the scikit-learn==1.1.1 is
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

mAPI | mAPV | mAPT | mAPIV | mAPIT | mAPIVT
-- | -- | -- | -- | -- | --
81.54 | 49.79 | 27.86 | 22.75 | 13.89 | 8.53

</body>
</html>

**Comment by nwoyecid** [comment]
Thank you for the information, we will inspect how the latest update of sklearn lib affects the behaviour of ivtmetrics. For the meantime, we encourage all users to stick with sklearn <= 1.02 for comparable results. Meanwhile, we will be rolling out a custom 'no library' implementation of AP metrics. This will replace the sklearn in our next release.

**Comment by nwoyecid** [comment]
Value issue with sklearn version update is now resolved in the ivtmetrics v0.1.1
Thank you
