### ISSUE TITLE
TensorFlow 2 code

### ISSUE THREAD

**Issue by IzzeddinTeeti** [CAMMA-public/rendezvous#7]
Hi,
I tried the Tensorflow implementation, but it did not work for me. I copied **run.py** to **tensorflow_2.x** and I set the directory to **tensorflow_2.x** then used `python run.py -t -e --data_dir="data folder" --dataset_variant=cholect50-challenge --version=1`. Did I do something wrong? Can you please guide me on how to run the TensorFlow implementation.

**Comment by nwoyecid** [comment]
Please note that you will need to follow the run.py in pytorch to re-implement the training script for tensorflow-2.x. Directly using a training script from another framework will obviously not work as tensorflow handles parameter optimization differently from pytorch.
