### ISSUE TITLE
Model release

### ISSUE THREAD

**Issue by gshuangchun** [CAMMA-public/rendezvous#8]
Hello,
Thank you for your nice work!
Could you please release the trained model and the used PyTorch hyperparameters as soon as possible?
Because the reported mAP on PyTorch implementation can not be reproduced.
![image](https://user-images.githubusercontent.com/73086275/194790465-0f6018d2-1034-4095-b8c2-599177af1a06.png)

**Comment by nwoyecid** [comment]
Soon
