### ISSUE TITLE
pos_weight

### ISSUE THREAD

**Issue by gshuangchun** [CAMMA-public/rendezvous#9]
Hi,
Thank you for your contribution!
Could you please release the code/details for BCELogitloss position weight calculation?

`# Or constant weights from average of the random sampling of the dataset: we found this to produce better result.`
`tool_weight = [0.93487068, 0.94234964, 0.93487068, 1.18448115, 1.02368339, 0.97974447]`
```
verb_weight = [0.60002400, 0.60002400, 0.60002400, 0.61682467, 0.67082683, 0.80163207, 0.70562823, 2.11208448,
               2.69230769, 0.60062402]
```

```
target_weight = [0.49752894, 0.52041527, 0.49752894, 0.51394739, 2.71899565, 1.75577963, 0.58509403, 1.25228034,
                 0.49752894, 2.42993134, 0.49802647, 0.87266576, 1.36074165, 0.50150917, 0.49802647]
```

`loss_fn_i = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(tool_weight).cuda())`
`loss_fn_v = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(verb_weight).cuda())`
`loss_fn_t = nn.BCEWithLogitsLoss(pos_weight=torch.tensor(target_weight).cuda())`

**Comment by nwoyecid** [comment]
Formula for the pos_weight calculation is given [here](https://arxiv.org/pdf/1812.01366.pdf)
